Update function response to data spikes to continue processing. Remov…
uafgeotools/lts_array pull request #14
Opened 2020-07-10 21:43 UTC by jwbishop

…es break statement.

A spike in the data (e.g. an electrical glitch) would appear with a time delay of 0 sec. across the array. Previously, *ltsva* would break the data processing loop in the presence of a spike, which inhibits processing flow. Now the spike is noted, but processing continues in the next window.

2020-07-12 22:42 UTC, liamtoney requested changes

2020-07-12 22:42 UTC, liamtoney commented on lts_array/ltsva.py
> +            print("Tdelays are equal. LTS algorithm not run. \
Perhaps this is more clear?
```suggestion
            print("Time delays are equal. LTS algorithm not run. \
```

2020-07-13 00:49 UTC, liamtoney approved these changes
Looks good now!

2020-07-13 16:36 UTC, davidfee5 approved these changes
Looks good to me as well. Thanks

2020-07-13 16:37 UTC, merged